### ISSUE TITLE
doesn't seems to work anymore

### ISSUE THREAD

**Issue by felipejoribeiro** [CloudSnorkel/serverless-pydeps#1]
i tried to use this in a project. I installed as recommended in the `README` and created the `requirements.txt` file.

When i run `sls deploy`, here's the output:

```
Service Information
service: kinlambda
stage: dev
region: us-east-2
stack: kinlambda-dev
resources: 16
api keys:
  None
endpoints:
  GET - xxxxxxxxx
functions:
  hello: kinlambda-dev-hello
layers:
  None
```
It doesn't work, as the function can´t import numpy. I can see that in the logs of the function.
But when i try to attach the layer manually to the function, with:
```
functions:
  hello:
    handler: handler.hello  
  layers:
    - xxxxxxx
  events:
      - http:
          method: GET
          path: /test
```
it creates an error telling that you can´t append the same layer two times to the same function implying that it is using the layer. But i can't import numpy nonetheless.
In the aws console i can se the the layer exists.

But the function isn't using the layer.
I would love to use this plugin, as it is does serious optimization. Thank you for the software.
